[package]
name = "commonmarker"
version = "1.0.0"
edition = "2021"
rust-version = "1.75.0"
publish = false

[dependencies]
magnus = "0.6"
comrak = { version = "0.20", features = ["shortcodes"] }
syntect = { version = "5.1", features = ["plist-load"] }
typed-arena = "2.0"

[lib]
name = "commonmarker"
crate-type = ["cdylib"]
